/* libDaltonLens - public domain library - http://daltonlens.org
                                  no warranty implied; use at your own risk

    Author: Nicolas Burrus <nicolas@burrus.name>

    LICENSE information at the end of the file.
*/

/*
    For more information about the math of these two algorithms
    see https://daltonlens.org/understanding-cvd-simulation/

    The notebook used to dump the precomputed matrices can be found
    in the DaltonLens-Python project:
    https://github.com/DaltonLens/DaltonLens-Python/blob/master/research/for-desktop/precomputed_matrices.ipynb
*/

#include "libDaltonLens.h"

#include <math.h>
#include <stddef.h>

/* Guard against invalid inputs to avoid silent garbage output or segfaults.
   Returns 1 if inputs are valid, 0 if the call should be a no-op. */
static int dl_validate_inputs(const unsigned char *srgba_image, size_t width, size_t height, float severity)
{
    if (srgba_image == NULL) return 0;
    if (width == 0 || height == 0) return 0;
    if (severity < 0.0f) return 0;
    if (severity > 1.0f) return 0;
    return 1;
}

/*
    From https://en.wikipedia.org/wiki/SRGB

    This is the standard used by most images and displays. This is the textbook
    implementation that uses powf.

    Define DL_USE_LUT before including libDaltonLens.h (or before this .c file) to
    use precomputed 256-entry lookup tables for the sRGB <-> linearRGB conversions.
    LUT mode trades 1KB of data memory for ~50% fewer powf() calls per pixel.
    Benchmark on your target hardware before committing to one path; on modern
    out-of-order CPUs the gain is often small and the LUT is less SIMD-friendly.
*/

#ifdef DL_USE_LUT

/* Precomputed linearRGB_from_sRGB for all 256 byte values.
   Generated by: for v in range(256): fv=v/255; print(fv/12.92 if fv<0.04045 else ((fv+0.055)/1.055)**2.4)
   WHY: Eliminates powf() on the hot encode path; breaks SIMD vectorization but
        is faster on scalar pipelines when the table fits in L1 cache (1KB). */
static const float dl_srgb_to_linear_lut[256] = {
    0.000000f, 0.000304f, 0.000607f, 0.000911f, 0.001214f, 0.001518f, 0.001821f, 0.002125f,
    0.002428f, 0.002732f, 0.003035f, 0.003347f, 0.003677f, 0.004025f, 0.004391f, 0.004777f,
    0.005182f, 0.005605f, 0.006049f, 0.006512f, 0.006995f, 0.007499f, 0.008023f, 0.008568f,
    0.009134f, 0.009721f, 0.010330f, 0.010960f, 0.011612f, 0.012286f, 0.012983f, 0.013702f,
    0.014444f, 0.015209f, 0.015996f, 0.016807f, 0.017642f, 0.018500f, 0.019382f, 0.020289f,
    0.021219f, 0.022174f, 0.023153f, 0.024158f, 0.025187f, 0.026241f, 0.027321f, 0.028426f,
    0.029557f, 0.030713f, 0.031896f, 0.033105f, 0.034340f, 0.035601f, 0.036889f, 0.038204f,
    0.039546f, 0.040915f, 0.042311f, 0.043735f, 0.045186f, 0.046665f, 0.048172f, 0.049707f,
    0.051269f, 0.052861f, 0.054480f, 0.056128f, 0.057805f, 0.059511f, 0.061246f, 0.063010f,
    0.064803f, 0.066626f, 0.068479f, 0.070360f, 0.072272f, 0.074214f, 0.076185f, 0.078187f,
    0.080220f, 0.082283f, 0.084376f, 0.086500f, 0.088656f, 0.090842f, 0.093059f, 0.095307f,
    0.097587f, 0.099899f, 0.102242f, 0.104616f, 0.107023f, 0.109462f, 0.111932f, 0.114435f,
    0.116971f, 0.119538f, 0.122139f, 0.124772f, 0.127438f, 0.130136f, 0.132868f, 0.135633f,
    0.138432f, 0.141263f, 0.144128f, 0.147027f, 0.149960f, 0.152926f, 0.155926f, 0.158961f,
    0.162029f, 0.165132f, 0.168269f, 0.171441f, 0.174647f, 0.177888f, 0.181164f, 0.184475f,
    0.187821f, 0.191202f, 0.194618f, 0.198069f, 0.201556f, 0.205079f, 0.208637f, 0.212231f,
    0.215861f, 0.219526f, 0.223228f, 0.226966f, 0.230740f, 0.234551f, 0.238398f, 0.242281f,
    0.246201f, 0.250158f, 0.254152f, 0.258183f, 0.262251f, 0.266356f, 0.270498f, 0.274677f,
    0.278894f, 0.283149f, 0.287441f, 0.291771f, 0.296138f, 0.300544f, 0.304987f, 0.309469f,
    0.313989f, 0.318547f, 0.323143f, 0.327778f, 0.332452f, 0.337164f, 0.341914f, 0.346704f,
    0.351533f, 0.356400f, 0.361307f, 0.366253f, 0.371238f, 0.376262f, 0.381326f, 0.386430f,
    0.391573f, 0.396755f, 0.401978f, 0.407241f, 0.412543f, 0.417885f, 0.423268f, 0.428690f,
    0.434154f, 0.439657f, 0.445201f, 0.450786f, 0.456411f, 0.462077f, 0.467784f, 0.473531f,
    0.479320f, 0.485150f, 0.491021f, 0.496933f, 0.502886f, 0.508881f, 0.514918f, 0.520996f,
    0.527115f, 0.533276f, 0.539479f, 0.545724f, 0.552011f, 0.558340f, 0.564712f, 0.571125f,
    0.577581f, 0.584079f, 0.590619f, 0.597202f, 0.603827f, 0.610496f, 0.617207f, 0.623961f,
    0.630757f, 0.637597f, 0.644480f, 0.651406f, 0.658375f, 0.665387f, 0.672443f, 0.679543f,
    0.686685f, 0.693872f, 0.701102f, 0.708376f, 0.715694f, 0.723055f, 0.730461f, 0.737911f,
    0.745404f, 0.752942f, 0.760525f, 0.768151f, 0.775822f, 0.783538f, 0.791298f, 0.799103f,
    0.806952f, 0.814847f, 0.822786f, 0.830770f, 0.838799f, 0.846873f, 0.854993f, 0.863157f,
    0.871367f, 0.879622f, 0.887923f, 0.896269f, 0.904661f, 0.913099f, 0.921582f, 0.930111f,
    0.938686f, 0.947307f, 0.955973f, 0.964686f, 0.973445f, 0.982251f, 0.991102f, 1.000000f
};

static inline float linearRGB_from_sRGB(unsigned char v)
{
    return dl_srgb_to_linear_lut[v];
}

/* sRGB encoding via inverse LUT: binary-search the forward LUT for nearest value.
   This is intentionally simple; for a production path a separate inverse LUT
   or the powf path below would be faster. */
static inline unsigned char sRGB_from_linearRGB(float v)
{
    if (v <= 0.f) return 0;
    if (v >= 1.f) return 255;
    /* Linear search from the expected range center is fast enough for 256 entries
       when the LUT fits in L1 cache. Replace with binary search if profiling shows
       this is a bottleneck. */
    int lo = 0, hi = 255;
    while (lo < hi) {
        int mid = (lo + hi + 1) / 2;
        if (dl_srgb_to_linear_lut[mid] <= v) lo = mid;
        else hi = mid - 1;
    }
    return (unsigned char)lo;
}

#else  /* !DL_USE_LUT -- default: exact powf path */

static inline float linearRGB_from_sRGB(unsigned char v)
{
    float fv = v / 255.f;
    if (fv < 0.04045f) return fv / 12.92f;
    return powf((fv + 0.055f) / 1.055f, 2.4f);
}

static inline unsigned char sRGB_from_linearRGB(float v)
{
    if (v <= 0.f) return 0;
    if (v >= 1.f) return 255;
    if (v < 0.0031308f) return 0.5f + (v * 12.92 * 255.f);
    return 0.f + 255.f * (powf(v, 1.f / 2.4f) * 1.055f - 0.055f);
}

#endif /* DL_USE_LUT */

/*
    Brettel 1997 precomputed parameters.

    LMS model
    =========

    These values use the sRGB standard to go from linearRGB to CIE XYZ, and the
    Smith & Pokorny 1975 model for CIE XYZ to LMS. This is the LMS model used by
    Viénot, Brettel and Mollon, but upgraded to use the sRGB standard used by
    modern monitors.

    Projection Planes
    =================

    These were computed using RGB white as the neutral element, not the
    equal-energy E. This option is commonly chosen by the Brettel
    implementations (including Vischeck), and it increases the range of colors
    that project within the sRGB gamut and avoids clipping too much.

    DaltonLens-Python Code to regenerate
    ====================================

    simulator = simulate.Simulator_Brettel1997(convert.LMSModel_sRGB_SmithPokorny75())
    simulator.dumpPrecomputedValues = True
    simulator.simulate_cvd(np.zeros((1,1,3), dtype=np.uint8), simulate.Deficiency.PROTAN, severity=1.0)
    simulator.simulate_cvd(np.zeros((1,1,3), dtype=np.uint8), simulate.Deficiency.DEUTAN, severity=1.0)
    simulator.simulate_cvd(np.zeros((1,1,3), dtype=np.uint8), simulate.Deficiency.TRITAN, severity=1.0)

    Alternative code to get the same output as Vischeck (as implemented in GIMP display filters):
    simulator = simulate.Simulator_Vischeck()
    simulator.dumpPrecomputedValues = True
    simulator.simulate_cvd(np.zeros((1,1,3), dtype=np.uint8), simulate.Deficiency.PROTAN, severity=1.0)
    simulator.simulate_cvd(np.zeros((1,1,3), dtype=np.uint8), simulate.Deficiency.DEUTAN, severity=1.0)
    simulator.simulate_cvd(np.zeros((1,1,3), dtype=np.uint8), simulate.Deficiency.TRITAN, severity=1.0)


    The implementation got simplified to minimize compute (with the
    exact same output), refer to 
    https://daltonlens.org/cvd-simulation-svg-filters/ for more details.
*/

/*
    These parameters combine the full projection pipeline for each half-plane so
    we don't need an explicit transform to the LMS space.

    To check on which plane the LMS point should project we also don't need to
    actually compute the LMS coordinates, and can do it directly in the RGB space.
*/
struct DLBrettel1997Params
{
    // Transformation using plane 1 == rgbFromLms . projection1 . lmsFromRgb
    float rgbCvdFromRgb_1[9];
    
    // Full transformation using plane 2 == rgbFromLms . projection2 . lmsFromRgb
    float rgbCvdFromRgb_2[9];

    // Normal of the separation plane to pick the right transform, already in the RGB space.
    // == normalInLms . lmsFromRgb
    float separationPlaneNormalInRgb[3];
};

static struct DLBrettel1997Params brettel_protan_params = {
    {
        0.14980, 1.19548, -0.34528,
        0.10764, 0.84864, 0.04372,
        0.00384, -0.00540, 1.00156,
    },
    {
        0.14570, 1.16172, -0.30742,
        0.10816, 0.85291, 0.03892,
        0.00386, -0.00524, 1.00139,
    },
    { 0.00048, 0.00393, -0.00441 }
};
static struct DLBrettel1997Params brettel_deutan_params = {
    {
        0.36477, 0.86381, -0.22858,
        0.26294, 0.64245, 0.09462,
        -0.02006, 0.02728, 0.99278,
    },
    {
        0.37298, 0.88166, -0.25464,
        0.25954, 0.63506, 0.10540,
        -0.01980, 0.02784, 0.99196,
    },
    { -0.00281, -0.00611, 0.00892 }
};
static struct DLBrettel1997Params brettel_tritan_params = {
    {
        1.01277, 0.13548, -0.14826,
        -0.01243, 0.86812, 0.14431,
        0.07589, 0.80500, 0.11911,
    },
    {
        0.93678, 0.18979, -0.12657,
        0.06154, 0.81526, 0.12320,
        -0.37562, 1.12767, 0.24796,
    },
    { 0.03901, -0.02788, -0.01113 }
};

void dl_simulate_cvd_brettel1997 (enum DLDeficiency deficiency, float severity, unsigned char* srgba_image, size_t width, size_t height, size_t bytesPerRow)
{
    if (!dl_validate_inputs(srgba_image, width, height, severity)) return;

    // Compute a default bytesPerRow if it wasn't specified.
    if (bytesPerRow == 0)
    {
        bytesPerRow = width * 4;
    }

    const struct DLBrettel1997Params* params = NULL;
    switch (deficiency)
    {
        case DLDeficiency_Protan:   params = &brettel_protan_params; break;
        case DLDeficiency_Deutan:   params = &brettel_deutan_params; break;
        case DLDeficiency_Tritan:   params = &brettel_tritan_params; break;
        default: return; /* ACHROMAT and BCM are not dichromacies; use their own functions */
    }

    for (size_t row = 0; row < height; ++row)
    {
        unsigned char* rowPtr = srgba_image + bytesPerRow*row;
        for (size_t col = 0; col < width*4; col += 4)
        {
            // rgb = linearRGB_from_sRGB(srgb)
            // alpha is untouched.
            const float rgb[3] = {
                linearRGB_from_sRGB(rowPtr[col + 0]),
                linearRGB_from_sRGB(rowPtr[col + 1]),
                linearRGB_from_sRGB(rowPtr[col + 2])
            };
            
            // Check on which plane we should project by comparing wih the separation plane normal.
            const float* n = params->separationPlaneNormalInRgb;
            const float dotWithSepPlane = rgb[0]*n[0] + rgb[1]*n[1] + rgb[2]*n[2];
            const float* rgbCvdFromRgb = (dotWithSepPlane >= 0 ? params->rgbCvdFromRgb_1 : params->rgbCvdFromRgb_2);

            float rgb_cvd[3] = {
                rgbCvdFromRgb[0]*rgb[0] + rgbCvdFromRgb[1]*rgb[1] + rgbCvdFromRgb[2]*rgb[2],
                rgbCvdFromRgb[3]*rgb[0] + rgbCvdFromRgb[4]*rgb[1] + rgbCvdFromRgb[5]*rgb[2],
                rgbCvdFromRgb[6]*rgb[0] + rgbCvdFromRgb[7]*rgb[1] + rgbCvdFromRgb[8]*rgb[2]
            };

            // Apply the severity factor as a linear interpolation.
            // It's the same to do it in the RGB space or in the LMS
            // space since it's a linear transform.
            rgb_cvd[0] = rgb_cvd[0]*severity + rgb[0]*(1.f-severity);
            rgb_cvd[1] = rgb_cvd[1]*severity + rgb[1]*(1.f-severity);
            rgb_cvd[2] = rgb_cvd[2]*severity + rgb[2]*(1.f-severity);

            // Encode as sRGB and write the result.
            rowPtr[col + 0] = sRGB_from_linearRGB(rgb_cvd[0]);
            rowPtr[col + 1] = sRGB_from_linearRGB(rgb_cvd[1]);
            rowPtr[col + 2] = sRGB_from_linearRGB(rgb_cvd[2]);
        }
    }
}

/*
    Viénot 1999 precomputed parameters.

    This follows the paper exactly, but using the modern sRGB standard to decode
    the input RGB values.

    Since there is only one projection plane, the entire pipeline can be reduced
    to a single 3x3 matrix multiplication in the linearRGB space.

    DaltonLens-Python Code to regenerate
    ====================================

    simulator =
    simulate.Simulator_Vienot1999(convert.LMSModel_sRGB_SmithPokorny75())
    simulator.dumpPrecomputedValues = True
    simulator.simulate_cvd(np.zeros((1,1,3), dtype=np.uint8), simulate.Deficiency.PROTAN, severity=1.0)
    simulator.simulate_cvd(np.zeros((1,1,3), dtype=np.uint8), simulate.Deficiency.DEUTAN, severity=1.0)
    simulator.simulate_cvd(np.zeros((1,1,3), dtype=np.uint8), simulate.Deficiency.TRITAN, severity=1.0)
*/

static float dl_vienot_protan_rgbCvd_from_rgb[] = {
    0.11238, 0.88762, 0.00000,
    0.11238, 0.88762, -0.00000,
    0.00401, -0.00401, 1.00000
};

static float dl_vienot_deutan_rgbCvd_from_rgb[] = {
    0.29275, 0.70725, 0.00000,
    0.29275, 0.70725, -0.00000,
    -0.02234, 0.02234, 1.00000
};

// WARNING: Viénot 1999 is not accurate for tritanopia. Use Brettel 1997 instead.
static float dl_vienot_tritan_rgbCvd_from_rgb[] = {
    1.00000, 0.14461, -0.14461,
    0.00000, 0.85924, 0.14076,
    -0.00000, 0.85924, 0.14076
};

void dl_simulate_cvd_vienot1999 (enum DLDeficiency deficiency, float severity, unsigned char* srgba_image, size_t width, size_t height, size_t bytesPerRow)
{
    if (!dl_validate_inputs(srgba_image, width, height, severity)) return;

    // Compute a default bytesPerRow if it wasn't specified.
    if (bytesPerRow == 0)
    {
        bytesPerRow = width * 4;
    }

    const float* rgbCvd_from_rgb = NULL;
    switch (deficiency)
    {
        case DLDeficiency_Protan:   rgbCvd_from_rgb = dl_vienot_protan_rgbCvd_from_rgb; break;
        case DLDeficiency_Deutan:   rgbCvd_from_rgb = dl_vienot_deutan_rgbCvd_from_rgb; break;
        case DLDeficiency_Tritan:   rgbCvd_from_rgb = dl_vienot_tritan_rgbCvd_from_rgb; break;
        default: return; /* ACHROMAT and BCM are not dichromacies; use their own functions */
    }

    for (size_t row = 0; row < height; ++row)
    {
        unsigned char* rowPtr = srgba_image + bytesPerRow*row;
        for (size_t col = 0; col < width*4; col += 4)
        {
            // rgb = linearRGB_from_sRGB(srgb)
            // alpha is untouched.
            float rgb[3] = {
                linearRGB_from_sRGB(rowPtr[col + 0]),
                linearRGB_from_sRGB(rowPtr[col + 1]),
                linearRGB_from_sRGB(rowPtr[col + 2])
            };
            
            // rgb_cvd = rgbCvd_from_rgb * rgb
            float rgb_cvd[3] = {
                rgbCvd_from_rgb[0]*rgb[0] + rgbCvd_from_rgb[1]*rgb[1] + rgbCvd_from_rgb[2]*rgb[2],
                rgbCvd_from_rgb[3]*rgb[0] + rgbCvd_from_rgb[4]*rgb[1] + rgbCvd_from_rgb[5]*rgb[2],
                rgbCvd_from_rgb[6]*rgb[0] + rgbCvd_from_rgb[7]*rgb[1] + rgbCvd_from_rgb[8]*rgb[2]
            };

            // Implement the severity factor as a linear interpolation.
            if (severity < 0.999f)
            {
                rgb_cvd[0] = severity*rgb_cvd[0] + (1.f - severity)*rgb[0];
                rgb_cvd[1] = severity*rgb_cvd[1] + (1.f - severity)*rgb[1];
                rgb_cvd[2] = severity*rgb_cvd[2] + (1.f - severity)*rgb[2];
            }

            // Write the result, encoded to sRGB
            rowPtr[col + 0] = sRGB_from_linearRGB(rgb_cvd[0]);
            rowPtr[col + 1] = sRGB_from_linearRGB(rgb_cvd[1]);
            rowPtr[col + 2] = sRGB_from_linearRGB(rgb_cvd[2]);
        }
    }
}

/* ---------------------------------------------------------
   dl_simulate_cvd_achromat
   Rod monochromacy (achromatopsia): all cones absent.
   Maps every pixel to its BT.709 photopic luminance.
   --------------------------------------------------------- */
void dl_simulate_cvd_achromat (float severity, unsigned char* srgba_image, size_t width, size_t height, size_t bytesPerRow)
{
    if (!dl_validate_inputs(srgba_image, width, height, severity)) return;
    if (bytesPerRow == 0) bytesPerRow = width * 4;

    for (size_t row = 0; row < height; ++row)
    {
        unsigned char* p = srgba_image + bytesPerRow * row;
        for (size_t col = 0; col < width * 4; col += 4)
        {
            const float r = linearRGB_from_sRGB(p[col + 0]);
            const float g = linearRGB_from_sRGB(p[col + 1]);
            const float b = linearRGB_from_sRGB(p[col + 2]);

            /* BT.709 photopic luminance (same weights as WCAG relative luminance) */
            const float Y = 0.2126f * r + 0.7152f * g + 0.0722f * b;

            /* All channels = Y; severity blends toward original */
            p[col + 0] = sRGB_from_linearRGB(Y * severity + r * (1.f - severity));
            p[col + 1] = sRGB_from_linearRGB(Y * severity + g * (1.f - severity));
            p[col + 2] = sRGB_from_linearRGB(Y * severity + b * (1.f - severity));
            /* alpha channel (p[col+3]) is intentionally untouched */
        }
    }
}

/* ---------------------------------------------------------
   dl_simulate_cvd_bcm
   Blue-cone monochromacy: L and M cones absent,
   S-cones + rods functional.

   Precomputed BCM matrix (SmithPokorny75, sRGB):
       from daltonlens import convert; import numpy as np
       model = convert.LMSModel_sRGB_SmithPokorny75()
       bt709 = np.array([0.2126, 0.7152, 0.0722])
       w = model.LMS_from_linearRGB @ np.ones(3)
       A = np.vstack([w[0]*bt709, w[1]*bt709, model.LMS_from_linearRGB[2]])
       BCM = model.linearRGB_from_LMS @ A
   white_lms ~= [0.65518, 0.34478, 0.01608]
   --------------------------------------------------------- */
static const float dl_bcm_rgb_from_rgb[9] = {
     0.17437f,  0.59636f,  0.22927f,  /* row 0 */
     0.24981f,  0.83088f, -0.08069f,  /* row 1 */
    -0.01452f,  0.00907f,  1.00546f,  /* row 2 */
};

void dl_simulate_cvd_bcm (float severity, unsigned char* srgba_image, size_t width, size_t height, size_t bytesPerRow)
{
    if (!dl_validate_inputs(srgba_image, width, height, severity)) return;
    if (bytesPerRow == 0) bytesPerRow = width * 4;

    const float* m = dl_bcm_rgb_from_rgb;

    for (size_t row = 0; row < height; ++row)
    {
        unsigned char* p = srgba_image + bytesPerRow * row;
        for (size_t col = 0; col < width * 4; col += 4)
        {
            const float r = linearRGB_from_sRGB(p[col + 0]);
            const float g = linearRGB_from_sRGB(p[col + 1]);
            const float b = linearRGB_from_sRGB(p[col + 2]);

            /* Apply BCM matrix */
            float rc = m[0]*r + m[1]*g + m[2]*b;
            float gc = m[3]*r + m[4]*g + m[5]*b;
            float bc = m[6]*r + m[7]*g + m[8]*b;

            /* Gamut fix: subtract most-negative channel, then clip max to 1.
               Matches Python convert.desaturate_linearRGB_to_fit_in_gamut().
               Must be done BEFORE severity blend (out-of-gamut values would
               corrupt the blend arithmetic otherwise). */
            float mn = rc;
            if (gc < mn) mn = gc;
            if (bc < mn) mn = bc;
            if (mn < 0.f) { rc -= mn; gc -= mn; bc -= mn; }
            if (rc > 1.f) rc = 1.f;
            if (gc > 1.f) gc = 1.f;
            if (bc > 1.f) bc = 1.f;

            /* Severity blend toward original */
            p[col + 0] = sRGB_from_linearRGB(rc * severity + r * (1.f - severity));
            p[col + 1] = sRGB_from_linearRGB(gc * severity + g * (1.f - severity));
            p[col + 2] = sRGB_from_linearRGB(bc * severity + b * (1.f - severity));
        }
    }
}

/*
   dl_simulate_cvd_machado2009

   Precomputed RGB matrices from:
     Machado, Oliveira & Fernandes (2009).
     "A physiologically-based model for simulation of color vision deficiency."
     IEEE Transactions on Visualization and Computer Graphics.

   Supports DLDeficiency_Protan, DLDeficiency_Deutan, and DLDeficiency_Tritan.
   Severity is a continuous value in [0.0, 1.0].  Internally the 11 precomputed
   matrices (severity 0.0, 0.1, ..., 1.0) are linearly interpolated.

   Algorithm matches Python Simulator_Machado2009 exactly.
   Matrices are precomputed for sRGB primaries with the Smith-Pokorny 1975
   LMS model; no LMS conversion is required at inference time.
*/

/* Row-major 3x3 matrices: m[row*3+col].  Index 0..10 = severity 0.0..1.0. */
static const float dl_machado_protan[11][9] = {
    { 1.000000f,  0.000000f, -0.000000f,  0.000000f,  1.000000f,  0.000000f, -0.000000f, -0.000000f,  1.000000f },
    { 0.856167f,  0.182038f, -0.038205f,  0.029342f,  0.955115f,  0.015544f, -0.002880f, -0.001563f,  1.004443f },
    { 0.734766f,  0.334872f, -0.069637f,  0.051840f,  0.919198f,  0.028963f, -0.004928f, -0.004209f,  1.009137f },
    { 0.630323f,  0.465641f, -0.095964f,  0.069181f,  0.890046f,  0.040773f, -0.006308f, -0.007724f,  1.014032f },
    { 0.539009f,  0.579343f, -0.118352f,  0.082546f,  0.866121f,  0.051332f, -0.007136f, -0.011959f,  1.019095f },
    { 0.458064f,  0.679578f, -0.137642f,  0.092785f,  0.846313f,  0.060902f, -0.007494f, -0.016807f,  1.024301f },
    { 0.385450f,  0.769005f, -0.154455f,  0.100526f,  0.829802f,  0.069673f, -0.007442f, -0.022190f,  1.029632f },
    { 0.319627f,  0.849633f, -0.169261f,  0.106241f,  0.815969f,  0.077790f, -0.007025f, -0.028051f,  1.035076f },
    { 0.259411f,  0.923008f, -0.182420f,  0.110296f,  0.804340f,  0.085364f, -0.006276f, -0.034346f,  1.040622f },
    { 0.203876f,  0.990338f, -0.194214f,  0.112975f,  0.794542f,  0.092483f, -0.005222f, -0.041043f,  1.046265f },
    { 0.152286f,  1.052583f, -0.204868f,  0.114503f,  0.786281f,  0.099216f, -0.003882f, -0.048116f,  1.051998f },
};

static const float dl_machado_deutan[11][9] = {
    { 1.000000f,  0.000000f, -0.000000f,  0.000000f,  1.000000f,  0.000000f, -0.000000f, -0.000000f,  1.000000f },
    { 0.866435f,  0.177704f, -0.044139f,  0.049567f,  0.939063f,  0.011370f, -0.003453f,  0.007233f,  0.996220f },
    { 0.760729f,  0.319078f, -0.079807f,  0.090568f,  0.889315f,  0.020117f, -0.006027f,  0.013325f,  0.992702f },
    { 0.675425f,  0.433850f, -0.109275f,  0.125303f,  0.847755f,  0.026942f, -0.007950f,  0.018572f,  0.989378f },
    { 0.605511f,  0.528560f, -0.134071f,  0.155318f,  0.812366f,  0.032316f, -0.009376f,  0.023176f,  0.986200f },
    { 0.547494f,  0.607765f, -0.155259f,  0.181692f,  0.781742f,  0.036566f, -0.010410f,  0.027275f,  0.983136f },
    { 0.498864f,  0.674741f, -0.173604f,  0.205199f,  0.754872f,  0.039929f, -0.011131f,  0.030969f,  0.980162f },
    { 0.457771f,  0.731899f, -0.189670f,  0.226409f,  0.731012f,  0.042579f, -0.011595f,  0.034333f,  0.977261f },
    { 0.422823f,  0.781057f, -0.203881f,  0.245752f,  0.709602f,  0.044646f, -0.011843f,  0.037423f,  0.974421f },
    { 0.392952f,  0.823610f, -0.216562f,  0.263559f,  0.690210f,  0.046232f, -0.011910f,  0.040281f,  0.971630f },
    { 0.367322f,  0.860646f, -0.227968f,  0.280085f,  0.672501f,  0.047413f, -0.011820f,  0.042940f,  0.968881f },
};

static const float dl_machado_tritan[11][9] = {
    { 1.000000f,  0.000000f, -0.000000f,  0.000000f,  1.000000f,  0.000000f, -0.000000f, -0.000000f,  1.000000f },
    { 0.926670f,  0.092514f, -0.019184f,  0.021191f,  0.964503f,  0.014306f,  0.008437f,  0.054813f,  0.936750f },
    { 0.895720f,  0.133330f, -0.029050f,  0.029997f,  0.945400f,  0.024603f,  0.013027f,  0.104707f,  0.882266f },
    { 0.905871f,  0.127791f, -0.033662f,  0.026856f,  0.941251f,  0.031893f,  0.013410f,  0.148296f,  0.838294f },
    { 0.948035f,  0.089490f, -0.037526f,  0.014364f,  0.946792f,  0.038844f,  0.010853f,  0.193991f,  0.795156f },
    { 1.017277f,  0.027029f, -0.044306f, -0.006113f,  0.958479f,  0.047634f,  0.006379f,  0.248708f,  0.744913f },
    { 1.104996f, -0.046633f, -0.058363f, -0.032137f,  0.971635f,  0.060503f,  0.001336f,  0.317922f,  0.680742f },
    { 1.193214f, -0.109812f, -0.083402f, -0.058496f,  0.979410f,  0.079086f, -0.002346f,  0.403492f,  0.598854f },
    { 1.257728f, -0.139648f, -0.118081f, -0.078003f,  0.975409f,  0.102594f, -0.003316f,  0.501214f,  0.502102f },
    { 1.278864f, -0.125333f, -0.153531f, -0.084748f,  0.957674f,  0.127074f, -0.000989f,  0.601151f,  0.399838f },
    { 1.255528f, -0.076749f, -0.178779f, -0.078411f,  0.930809f,  0.147602f,  0.004733f,  0.691367f,  0.303900f },
};

void dl_simulate_cvd_machado2009 (enum DLDeficiency deficiency, float severity, unsigned char* srgba_image, size_t width, size_t height, size_t bytesPerRow)
{
    if (!dl_validate_inputs(srgba_image, width, height, severity)) return;

    /* Select the matrix table for this deficiency. */
    const float (*table)[9];
    switch (deficiency)
    {
        case DLDeficiency_Protan:  table = dl_machado_protan;  break;
        case DLDeficiency_Deutan:  table = dl_machado_deutan;  break;
        case DLDeficiency_Tritan:  table = dl_machado_tritan;  break;
        default: return; /* ACHROMAT and BCM are not supported */
    }

    /* Interpolate between the two nearest precomputed matrices.
       alpha matches the Python formula: severity - lower*0.1 in range [0, 0.1].
       (Python: alpha = severity - severity_lower/10.0; NOT normalised to [0,1].) */
    int lower = (int)(severity * 10.0f);
    if (lower < 0)  lower = 0;
    if (lower > 10) lower = 10;
    int upper = (lower < 10) ? lower + 1 : 10;
    float alpha = severity - (float)lower * 0.1f;

    float m[9];
    for (int i = 0; i < 9; ++i)
        m[i] = (1.0f - alpha) * table[lower][i] + alpha * table[upper][i];

    if (bytesPerRow == 0) bytesPerRow = width * 4;

    for (size_t row = 0; row < height; ++row)
    {
        unsigned char* p = srgba_image + bytesPerRow * row;
        for (size_t col = 0; col < width * 4; col += 4)
        {
            const float r = linearRGB_from_sRGB(p[col + 0]);
            const float g = linearRGB_from_sRGB(p[col + 1]);
            const float b = linearRGB_from_sRGB(p[col + 2]);
            const float rc = m[0]*r + m[1]*g + m[2]*b;
            const float gc = m[3]*r + m[4]*g + m[5]*b;
            const float bc = m[6]*r + m[7]*g + m[8]*b;
            p[col + 0] = sRGB_from_linearRGB(rc);
            p[col + 1] = sRGB_from_linearRGB(gc);
            p[col + 2] = sRGB_from_linearRGB(bc);
        }
    }
}

void dl_simulate_cvd (enum DLDeficiency deficiency, float severity, unsigned char* srgba_image, size_t width, size_t height, size_t bytesPerRow)
{
    if (!dl_validate_inputs(srgba_image, width, height, severity)) return;

    switch (deficiency)
    {
        case DLDeficiency_Tritan:
            /* Viénot 1999 is not accurate for tritanopia; use Brettel 1997. */
            dl_simulate_cvd_brettel1997(deficiency, severity, srgba_image, width, height, bytesPerRow);
            break;
        case DLDeficiency_Achromat:
            dl_simulate_cvd_achromat(severity, srgba_image, width, height, bytesPerRow);
            break;
        case DLDeficiency_BCM:
            dl_simulate_cvd_bcm(severity, srgba_image, width, height, bytesPerRow);
            break;
        case DLDeficiency_Protan:
        case DLDeficiency_Deutan:
        default:
            /* Use Machado 2009 for anomalous trichromacy (severity < 1); Vienot
               at full severity matches Simulator_AutoSelect in DaltonLens-Python. */
            if (severity >= 0.9999f)
                dl_simulate_cvd_vienot1999(deficiency, severity, srgba_image, width, height, bytesPerRow);
            else
                dl_simulate_cvd_machado2009(deficiency, severity, srgba_image, width, height, bytesPerRow);
            break;
    }
}

/*
    LICENSE

    This is free and unencumbered software released into the public domain.

    Anyone is free to copy, modify, publish, use, compile, sell, or
    distribute this software, either in source code form or as a compiled
    binary, for any purpose, commercial or non-commercial, and by any
    means.

    In jurisdictions that recognize copyright laws, the author or authors
    of this software dedicate any and all copyright interest in the
    software to the public domain. We make this dedication for the benefit
    of the public at large and to the detriment of our heirs and
    successors. We intend this dedication to be an overt act of
    relinquishment in perpetuity of all present and future rights to this
    software under copyright law.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
    IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
    OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
    OTHER DEALINGS IN THE SOFTWARE.

    For more information, please refer to <https://unlicense.org>
*/
