#!/usr/bin/env python3
"""
Generate machine-checkable repo stats from tracked files.
"""

from __future__ import annotations

import argparse
import json
import subprocess
from collections import Counter
from pathlib import Path, PurePosixPath


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_JSON_OUTPUT = REPO_ROOT / "docs" / "generated" / "repo_stats.json"
DEFAULT_MD_OUTPUT = REPO_ROOT / "docs" / "generated" / "repo_stats.md"


def tracked_repo_paths(repo_root: Path = REPO_ROOT) -> list[str]:
    try:
        result = subprocess.run(
            ["git", "-C", str(repo_root), "ls-files"],
            check=True,
            capture_output=True,
            text=True,
        )
    except (FileNotFoundError, subprocess.CalledProcessError):
        return sorted(
            path.relative_to(repo_root).as_posix()
            for path in repo_root.rglob("*")
            if path.is_file() and ".git" not in path.parts
        )
    return sorted(line for line in result.stdout.splitlines() if line.strip())


def _count_matching(paths: list[str], predicate) -> int:
    return sum(1 for rel_path in paths if predicate(rel_path))


def _is_top_level_papers_markdown(rel_path: str) -> bool:
    path = PurePosixPath(rel_path)
    return path.parent == PurePosixPath("papers") and path.suffix == ".md"


def _is_research_markdown(rel_path: str) -> bool:
    return rel_path.startswith("research/") and rel_path.endswith(".md")


def _is_source_cache_doc(rel_path: str) -> bool:
    return rel_path.startswith("docs/external_sources/") and rel_path.endswith(
        "_source_cache.md"
    )


def _is_primary_source_notes(rel_path: str) -> bool:
    return rel_path.startswith("research/") and rel_path.endswith(
        "primary_source_notes.md"
    )


def _pdf_topic_counts(paths: list[str]) -> dict[str, int]:
    counts: Counter[str] = Counter()
    for rel_path in paths:
        if not rel_path.startswith("papers/downloads/") or not rel_path.endswith(
            ".pdf"
        ):
            continue
        parts = PurePosixPath(rel_path).parts
        if len(parts) >= 3:
            counts[parts[2]] += 1
    return dict(sorted(counts.items()))


def generate_repo_stats(repo_root: Path = REPO_ROOT) -> dict:
    paths = tracked_repo_paths(repo_root)
    pdf_by_topic = _pdf_topic_counts(paths)
    metrics = {
        "canonical_pdf_count": _count_matching(
            paths,
            lambda rel_path: rel_path.startswith("papers/downloads/")
            and rel_path.endswith(".pdf"),
        ),
        "top_level_papers_markdown_count": _count_matching(
            paths, _is_top_level_papers_markdown
        ),
        "research_markdown_count": _count_matching(paths, _is_research_markdown),
        "source_cache_doc_count": _count_matching(paths, _is_source_cache_doc),
        "primary_source_notes_count": _count_matching(paths, _is_primary_source_notes),
        "source_asset_pdf_count": _count_matching(
            paths,
            lambda rel_path: rel_path.startswith("datasets/source_assets/")
            and rel_path.endswith(".pdf"),
        ),
    }
    return {
        "schema_version": 1,
        "count_basis": "tracked_repo_files",
        "metrics": metrics,
        "pdf_by_topic": pdf_by_topic,
        "paths": {
            "canonical_pdf_root": "papers/downloads/",
            "source_cache_glob": "docs/external_sources/*_source_cache.md",
            "primary_source_notes_glob": "research/**/primary_source_notes.md",
        },
    }


def render_repo_stats_markdown(stats: dict) -> str:
    lines = [
        "# Generated Repo Stats",
        "",
        "This file is generated by `tools/repo_stats.py`. Do not hand-edit the counts.",
        "",
        "## Metrics",
        "",
        "| Metric | Value |",
        "|--------|-------|",
    ]
    for key, value in stats["metrics"].items():
        lines.append(f"| `{key}` | {value} |")
    lines.extend(
        [
            "",
            "## Canonical PDF Counts By Topic",
            "",
            "| Topic | PDF Count |",
            "|-------|-----------|",
        ]
    )
    for topic, count in stats["pdf_by_topic"].items():
        lines.append(f"| `{topic}` | {count} |")
    lines.extend(
        [
            "",
            "## Count Basis",
            "",
            "- tracked repo files only",
            "- canonical literature counted from `papers/downloads/**/*.pdf`",
            "- top-level paper docs counted from `papers/*.md`",
            "- research docs counted from `research/**/*.md`",
            "",
            "## What Is NOT Counted Here",
            "",
            "Compendium entry counts (the paper totals listed in `papers/*.md` narrative",
            "documents such as `colorblindness_algorithms_compendium.md`) are NOT",
            "machine-generated here. Those files use heterogeneous structures",
            "(numbered lists, `###` section headers, bold author blocks) that require",
            "a format-specific parser per file to count accurately. The prose counts",
            "in those files use `+` qualifiers (e.g., `50+`) to signal that they are",
            "approximate. If compendium entry counts begin drifting materially, add a",
            "dedicated counting function here per file using the file's native marker",
            "pattern (see T098 in `docs/task-ledger.md`).",
        ]
    )
    return "\n".join(lines) + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate machine-checkable repo stats."
    )
    parser.add_argument(
        "--repo-root",
        default=str(REPO_ROOT),
        help="Override the repository root.",
    )
    parser.add_argument(
        "--output-json",
        default=None,
        help="Optional path to write JSON stats.",
    )
    parser.add_argument(
        "--output-md",
        default=None,
        help="Optional path to write Markdown stats.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    repo_root = Path(args.repo_root).resolve()
    stats = generate_repo_stats(repo_root)
    rendered_json = json.dumps(stats, indent=2, sort_keys=True) + "\n"
    rendered_md = render_repo_stats_markdown(stats)
    if args.output_json:
        output_json = Path(args.output_json)
        output_json.parent.mkdir(parents=True, exist_ok=True)
        output_json.write_text(rendered_json, encoding="utf-8")
    if args.output_md:
        output_md = Path(args.output_md)
        output_md.parent.mkdir(parents=True, exist_ok=True)
        output_md.write_text(rendered_md, encoding="utf-8")
    if not args.output_json and not args.output_md:
        print(rendered_json, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
